# NumPy

## Reference
* [Universal functions (ufunc)](https://numpy.org/doc/stable/reference/ufuncs.html)

## Array

In [1]:
import numpy as np

In [2]:
matrix = [[1,2,3],
           [4,5,6],
           [7,8,9]]
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [5]:
# Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
# Uniform distribution
np.random.rand(3,3)

array([[0.53133617, 0.19332865, 0.38240558],
       [0.18882935, 0.09620901, 0.54869015],
       [0.92486328, 0.55030132, 0.62817771]])

In [7]:
# Normal distribution
np.random.randn(3,3)

array([[ 1.44724426,  2.03912148, -1.06460273],
       [ 1.49641152, -0.77070533,  0.45894669],
       [-0.29342291, -0.71496544,  0.28987504]])

In [8]:
np.random.randint(1, 100, 5)

array([64, 66, 82, 51, 41])

In [9]:
arr = np.arange(0,11, 2)
arr

array([ 0,  2,  4,  6,  8, 10])

In [10]:
# Referencing an array
slice_of_arr = arr[1:4]
slice_of_arr     # Note: This is a pointer not a copy

array([2, 4, 6])

In [11]:
slice_of_arr[:2] = 0
slice_of_arr

array([0, 0, 6])

In [12]:
arr

array([ 0,  0,  0,  6,  8, 10])

In [13]:
# Copying an array
copy_of_arr = arr.copy()
copy_of_arr

array([ 0,  0,  0,  6,  8, 10])

In [14]:
arr = arr.reshape(2,3)
arr

array([[ 0,  0,  0],
       [ 6,  8, 10]])

In [15]:
arr.max()

10

In [16]:
arr.argmax()     # 10 is at [1, 2]. argmax = col*1 + 2

5

In [17]:
arr.shape

(2, 3)

In [18]:
arr.dtype

dtype('int32')

In [19]:
arr[1,1]     # Use this notation over arr[1][1] becuz it works with slicing too.

8

In [20]:
arr[:2,1:]

array([[ 0,  0],
       [ 8, 10]])

In [21]:
bool_arr = arr > 6
bool_arr

array([[False, False, False],
       [False,  True,  True]])

In [22]:
arr[bool_arr]

array([ 8, 10])

## Array Operations

In [23]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
# Arithematic Operations
arr + 7
arr ** 2
arr + arr
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [25]:
arr / arr     # 0/0 case

C:\Users\somahato\AppData\Local\Temp\ipykernel_21032\599831216.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr     # 0/0 case


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [26]:
1 / arr

C:\Users\somahato\AppData\Local\Temp\ipykernel_21032\1528351372.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [27]:
np.square(arr)
np.sqrt(arr)
np.sin(arr)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [28]:
np.log(arr)

C:\Users\somahato\AppData\Local\Temp\ipykernel_21032\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [29]:
np.max(arr)
np.mean(arr)
np.median(arr)

5.0